# Generated by Django 3.2.3 on 2021-09-08 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('text_field', 'Ответ текстом'), ('radio', 'Один вариант'), ('check_boxes', 'Выбор нескольких вариантов')], max_length=20, verbose_name='Тип вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вариант ответа')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('many_choice', models.ManyToManyField(related_name='many_answer', to='survey.Choice')),
                ('one_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_answer', to='survey.choice')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
