# Generated by Django 3.2.3 on 2021-09-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210910_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questions',
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='survey.survey'),
        ),
    ]
