# Generated by Django 3.2.3 on 2021-09-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210914_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
